use std::path::{Path, PathBuf};
use ignore::gitignore::{Gitignore, GitignoreBuilder};

/// Path components (lowercase) that are **always** ignored, regardless of any ignore-file
/// configuration.  These directories are generated by Unreal Engine, build tools, and IDEs
/// and will never contain source files that need to be re-scanned.
const HARDCODED_IGNORED: &[&str] = &[
    "binaries",
    "intermediate",
    "saved",
    "deriveddatacache",
    "build",        // UE build tool output (not the Source/*/Build sub-dirs)
    ".vs",
    ".git",
    ".svn",
    "node_modules",
    "__pycache__",
];

/// Per-project file-watcher filter.
///
/// Determines whether a path change event should be forwarded to `handle_file_change`.
/// Layers (checked in order, cheapest first):
///
/// 1. **Hardcoded** – directory names above (Unreal/IDE generated dirs, always ignored)
/// 2. **`.unlignore`** – project-local custom patterns, gitignore syntax, highest user priority
/// 3. **`.gitignore`** – standard Git ignore file at the project root
/// 4. **`.p4ignore`** (or `$P4IGNORE`) – Perforce ignore file, parsed as gitignore syntax
pub struct WatcherFilter {
    root: PathBuf,
    /// Combined gitignore rules from .unlignore / .gitignore / .p4ignore
    combined: Option<Gitignore>,
}

impl WatcherFilter {
    /// Build a `WatcherFilter` for the given `project_root` directory.
    /// Silently skips any file that does not exist.
    pub fn build(project_root: &Path) -> Self {
        let mut builder = GitignoreBuilder::new(project_root);

        // .unlignore – project-local overrides (highest priority)
        try_add(&mut builder, project_root, ".unlignore");

        // .gitignore – standard git ignores
        try_add(&mut builder, project_root, ".gitignore");

        // .p4ignore – Perforce ignores (respect P4IGNORE env var)
        let p4_name = std::env::var("P4IGNORE").unwrap_or_else(|_| ".p4ignore".to_string());
        try_add(&mut builder, project_root, &p4_name);

        let combined = match builder.build() {
            Ok(gi) if gi.num_ignores() > 0 => Some(gi),
            _ => None,
        };

        Self { root: project_root.to_path_buf(), combined }
    }

    /// Returns `true` when the path should be **ignored** (no watcher action needed).
    pub fn should_ignore(&self, path: &Path) -> bool {
        // Layer 1: hardcoded fast-path – O(components) with no allocations on the hot path.
        if should_ignore_fast(path) {
            return true;
        }

        // Layer 2-4: ignore-file rules.
        if let Some(gi) = &self.combined {
            if gitignore_matches(gi, path, &self.root) {
                return true;
            }
        }

        false
    }
}

/// Fast, stateless check: returns `true` if any path component matches a hardcoded ignored
/// directory name.  Called in the hot event-loop path (before any lock acquisition).
pub fn should_ignore_fast(path: &Path) -> bool {
    path.components().any(|c| {
        c.as_os_str()
            .to_str()
            .map_or(false, |s| HARDCODED_IGNORED.contains(&s.to_lowercase().as_str()))
    })
}

// ── helpers ────────────────────────────────────────────────────────────────────

/// Add an ignore file to `builder`, logging on success / warning on parse error.
fn try_add(builder: &mut GitignoreBuilder, root: &Path, name: &str) {
    let path = root.join(name);
    if !path.exists() {
        return;
    }
    match builder.add(&path) {
        None    => tracing::info!("WatcherFilter: loaded {}", name),
        Some(e) => tracing::warn!("WatcherFilter: could not parse {}: {}", name, e),
    }
}

/// Check `path` (and each of its ancestors relative to `root`) against `gi`.
///
/// This is necessary because gitignore patterns like `Saved/` match the *directory itself*,
/// not every file underneath it.  By walking up the component chain we correctly detect
/// `Saved/Logs/UE4.log` as matching the `Saved/` rule.
fn gitignore_matches(gi: &Gitignore, abs_path: &Path, root: &Path) -> bool {
    let rel = match abs_path.strip_prefix(root) {
        Ok(r)  => r,
        Err(_) => return false,
    };

    let mut current: &Path = rel;
    loop {
        // Check both as-file and as-directory (for patterns ending in `/`)
        if matches!(gi.matched(current, false), ignore::Match::Ignore(_)) { return true; }
        if matches!(gi.matched(current, true),  ignore::Match::Ignore(_)) { return true; }

        match current.parent() {
            Some(p) if !p.as_os_str().is_empty() => current = p,
            _ => break,
        }
    }
    false
}
